In [1]:
import numpy as np

In [2]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

In [3]:
np.dot(X, W1)

array([0.2, 0.5, 0.8])

In [4]:
class Relu:
    def __init__(self):
        self.mask = None
    
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout
        
        return dx

In [5]:
x = np.array([[1.0, -0.5], [-2.0, 3.0]])

In [7]:
mask = (x <= 0)
mask

array([[False,  True],
       [ True, False]])

In [8]:
x[mask]

array([-0.5, -2. ])

In [10]:
relu = Relu()

In [11]:
relu.forward(x)

array([[1., 0.],
       [0., 3.]])

In [12]:
relu.backward(x)

array([[1., 0.],
       [0., 3.]])