In [18]:
function sigmoid(x)
    println( (1 .+ exp.(-x)))
    b = 1 / (1 .+ exp.(-x))
    return 1 ./ (1 .+ exp.(-x))
end

sigmoid (generic function with 1 method)

In [19]:
sigmoid([-1.0, 1.0, 2.0])

[3.718281828459045, 1.3678794411714423, 1.1353352832366128]


3-element Array{Float64,1}:
 0.2689414213699951
 0.7310585786300049
 0.8807970779778823

In [20]:
1 / [3.718281828459045, 1.3678794411714423, 1.1353352832366128]

1×3 LinearAlgebra.Transpose{Float64,Array{Float64,1}}:
 0.218907  0.0805312  0.0668407

In [1]:
 1 / [2.0, 10.0]

1×2 LinearAlgebra.Transpose{Float64,Array{Float64,1}}:
 0.0192308  0.0961538

In [22]:
 1 ./ [5.0, 10.0]

2-element Array{Float64,1}:
 0.2
 0.1

"/ "と"./"で計算方法が違う。broadcastしたいなら./を使う。 a / bは配列に対して演算すると a * inv(b)を表すので注意が必要。

In [10]:
X = [1.0, 0.5]

2-element Array{Float64,1}:
 1.0
 0.5

In [11]:
typeof(X)

Array{Float64,1}

In [12]:
W1 = [0.1 0.3 0.5;
            0.2 0.4 0.6
            ]

2×3 Array{Float64,2}:
 0.1  0.3  0.5
 0.2  0.4  0.6

In [13]:
B1 = [0.1 0.2 0.3]

3-element Array{Float64,1}:
 0.1
 0.2
 0.3

In [18]:
dot(X' * W1)

LoadError: UndefVarError: dot not defined

In [19]:
using LinearAlgebra

In [25]:
X = [1.0 0.5]
W1 = [0.1 0.3 0.5;
            0.2 0.4 0.6]

2×3 Array{Float64,2}:
 0.1  0.3  0.5
 0.2  0.4  0.6

In [47]:
(X * W1)' + B1

3×1 Array{Float64,2}:
 0.30000000000000004
 0.7
 1.1

In [51]:
A1 = X * W1 + B1'

1×3 Array{Float64,2}:
 0.3  0.7  1.1

In [6]:
a = [1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [7]:
b = [1 2;3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [8]:
c = [1 2 3 4; 5 6 7 8]

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [11]:
a * c'

1×2 Array{Int64,2}:
 30  70

In [25]:
d = reshape(b', 4, 1)

4×1 reshape(::LinearAlgebra.Adjoint{Int64,Array{Int64,2}}, 4, 1) with eltype Int64:
 1
 2
 3
 4

In [26]:
a == d

false

In [27]:
d' * c'

1×2 Array{Int64,2}:
 30  70

In [28]:
e = [0.09709864 0.0002760582 0.053996764 0.0027928047 0.31670216 0.026006417 0.08908114 0.023497537 0.06351552 0.32703304]

1×10 Array{Float64,2}:
 0.0970986  0.000276058  0.0539968  …  0.0234975  0.0635155  0.327033

In [32]:
findmax(e)[2][2]

10

In [34]:
accuracy = 0
for i in 1:10
    if i == 2
        accuracy += 1
    end
end
accuracy

1

In [4]:
a = [1 2 3;4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [8]:
b = [2 4]

1×2 Array{Int64,2}:
 2  4

In [9]:
b * a

1×3 Array{Int64,2}:
 18  24  30

In [10]:
c = [2;4]

2-element Array{Int64,1}:
 2
 4

In [12]:
d = reshape(c, 1, length(c))

1×2 Array{Int64,2}:
 2  4

In [13]:
d * a

1×3 Array{Int64,2}:
 18  24  30

In [14]:
typeof(d)

Array{Int64,2}

In [18]:
length(a[:, 1])

2

In [19]:
d

1×2 Array{Int64,2}:
 2  4

In [20]:
a

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [21]:
d * a

1×3 Array{Int64,2}:
 18  24  30

In [22]:
g = [1 2 3 4 5 6]

1×6 Array{Int64,2}:
 1  2  3  4  5  6

In [29]:
g = reshape(g, 3, 2)

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [28]:
g[1, :]

3-element Array{Int64,1}:
 1
 3
 5

In [32]:
function meanSquared(y, t)
    return 0.5 .* sum((y .- t) .^2)
end

meanSquared (generic function with 1 method)

In [41]:
function crossEntropy(y, t)
    delta = 1e-7
    return sum(t .* log.(y .+ delta))
end

crossEntropy (generic function with 1 method)

In [42]:
t = [0 0 1 0 0 0 0 0 0 0]
y = [0.1 0.05 0.1 0.0 0.05 0.1 0.0 0.6 0.0 0.0]

crossEntropy(y, t)

-2.302584092994546

In [51]:
rand([0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8])

0.1

In [52]:
using StatsBase

In [57]:
StatsBase.sample(1:1000, 5)

5-element Array{Int64,1}:
 693
 662
  42
 181
 908

In [1]:
a = [
    1 2 3 4 5 6;
    7 8 9 10 11 12
]

2×6 Array{Int64,2}:
 1  2  3   4   5   6
 7  8  9  10  11  12

In [4]:
# dimの取得
length(a[:, 1])

2

In [5]:
eltype(a)

Int64

In [6]:
size(a)

(2, 6)

In [8]:
ndims(a)

2

LoadError: UndefVarError: linspace not defined

In [16]:
b = [0.1:0.2:1.1]

1-element Array{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},1}:
 0.1:0.2:1.1

In [17]:
for i in 1:length(b)
    println(b[i])
end

0.1:0.2:1.1


In [22]:
a = range(1,10, step=2)

1:2:9

In [23]:
a

1:2:9

In [27]:
num = [n for n = 0.0:0.1:20]

201-element Array{Float64,1}:
  0.0
  0.1
  0.2
  0.3
  0.4
  0.5
  0.6
  0.7
  0.8
  0.9
  1.0
  1.1
  1.2
  ⋮
 18.9
 19.0
 19.1
 19.2
 19.3
 19.4
 19.5
 19.6
 19.7
 19.8
 19.9
 20.0

In [3]:
a = [1 2 3 4 5 6;
        7 8 9 10 11 12]


2×6 Array{Int64,2}:
 1  2  3   4   5   6
 7  8  9  10  11  12

In [4]:
size(a)

(2, 6)

In [5]:
zeros(size(a))

2×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [10]:
for i in 1:ndims(a)
    println(i)
end

1
2


In [11]:
d = [1 2]

1×2 Array{Int64,2}:
 1  2

In [12]:
d[1, :]

2-element Array{Int64,1}:
 1
 2

In [13]:
function ag(x, y=1, z=2)
    return x + y + z
end

ag (generic function with 3 methods)

In [14]:
b = ag(1)

4

In [18]:
ag(1, 2, 3)

6

In [22]:
randn(2, 3)

2×3 Array{Float64,2}:
 0.361594  -0.714444   0.426311
 0.160077   0.237811  -2.34489